Test cases for '7-base_geometry'
================================

Test cases for two methods of the class BaseGeometry
----------------------------------------------------

Import module
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Cases to be evaluated:

>>> bg = BaseGeometry()

Case #1: value is type list
>>> bg.integer_validator("name", [1, 1])
Traceback (most recent call last):
TypeError: lst must be an integer

Case #2: Value is type string
>>> bg.integer_validator("name", "Tyler")
Traceback (most recent call last):
TypeError: name must be an integer

Case #3: Value is type tuple
>>> bg.integer_validator("name", (1 ,1))
Traceback (most recent call last):
TypeError: tup must be an integer

Case #4: Value is type float
>>> bg.integer_validator("name", 7.7)
Traceback (most recent call last):
TypeError: float must be an integer

Case #5: Value is type None
>>> bg.integer_validator("name", None)
Traceback (most recent call last):
TypeError: Nothing must be an integer

Case #6: Value is type boolean
>>> bg.integer_validator("name", True)
Traceback (most recent call last):
TypeError: boolean must be an integer

Case #7: Value is less than 0
>>> bg.integer_validator("name", -4)
Traceback (most recent call last):
ValueError: distance must be greater than 0

Case #8: Value is 0
>>> bg.integer_validator("name", 0)
Traceback (most recent call last):
ValueError: distance must be greater than 0

Case #9: No arguments
>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Case #10: Only one argument
>>> bg.integer_validator("name")
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

Case #11: More than two arguments
>>> bg.integer_validator("name", 1, 1)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given

Case #12: Test method 'area()'
>>> print(bg.area())
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg.integer_validator("name", 2)
